import type { ToolSet } from './toolset'
import type { TracePackageOutput } from './tracePackage'

export interface Message<T = unknown> {
  type: string
  data?: T
  requestId?: string
}

export interface Response<T = unknown> {
  success: boolean
  data?: T
  error?: string
}

export type TracePackageExportRequest = {
  readonly toolSet: ToolSet
}

export type TracePackageExportResult = TracePackageOutput

// ===== Side Panel → Background =====
export const MSG = {
  // 录制控制
  START_RECORDING: 'START_RECORDING',
  PAUSE_RECORDING: 'PAUSE_RECORDING',
  RESUME_RECORDING: 'RESUME_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  GET_RECORDING_STATUS: 'GET_RECORDING_STATUS',

  // 分析
  ANALYZE_STRUCTURAL: 'ANALYZE_STRUCTURAL',
  ANALYZE_NODE_ROLES: 'ANALYZE_NODE_ROLES',

  GENERATE_TRACE_PACKAGE: 'GENERATE_TRACE_PACKAGE',

  // 工具集
  TOOLSET_LIST: 'TOOLSET_LIST',
  TOOLSET_CREATE: 'TOOLSET_CREATE',
  TOOLSET_LOAD: 'TOOLSET_LOAD',
  TOOLSET_SAVE: 'TOOLSET_SAVE',
  TOOLSET_DELETE: 'TOOLSET_DELETE',

  // 回溯重放
  REPLAY_START: 'REPLAY_START',
  REPLAY_ABORT: 'REPLAY_ABORT',

  // 选择器拾取
  START_SELECTOR_PICKER: 'START_SELECTOR_PICKER',
  STOP_SELECTOR_PICKER: 'STOP_SELECTOR_PICKER',
  INFER_SELECTOR_PATTERN: 'INFER_SELECTOR_PATTERN',
  LOOP_TARGET_PREVIEW_TEST: 'LOOP_TARGET_PREVIEW_TEST',
  LOOP_TARGET_PREVIEW_SCAN: 'LOOP_TARGET_PREVIEW_SCAN',
  START_CONTENT_EXTRACT_PICKER: 'START_CONTENT_EXTRACT_PICKER',
  STOP_CONTENT_EXTRACT_PICKER: 'STOP_CONTENT_EXTRACT_PICKER',
  START_UPLOAD_PICKER: 'START_UPLOAD_PICKER',
  STOP_UPLOAD_PICKER: 'STOP_UPLOAD_PICKER',

  // 悬停拾取
  START_HOVER_PICKER: 'START_HOVER_PICKER',
  STOP_HOVER_PICKER: 'STOP_HOVER_PICKER',

  // 等待元素拾取
  START_WAIT_ELEMENT_PICKER: 'START_WAIT_ELEMENT_PICKER',
  STOP_WAIT_ELEMENT_PICKER: 'STOP_WAIT_ELEMENT_PICKER',

  // 选择器测试高亮
  TEST_SELECTOR_HIGHLIGHT: 'TEST_SELECTOR_HIGHLIGHT',
} as const

// ===== Background → Side Panel (事件推送) =====
export const EVENT = {
  ACTION_RECORDED: 'ACTION_RECORDED',
  ACTION_UPDATED: 'ACTION_UPDATED',
  RECORDING_STARTED: 'RECORDING_STARTED',
  RECORDING_PAUSED: 'RECORDING_PAUSED',
  RECORDING_RESUMED: 'RECORDING_RESUMED',
  RECORDING_STOPPED: 'RECORDING_STOPPED',
  TAB_NAVIGATED: 'TAB_NAVIGATED',
  REPLAY_STEP_RESULT: 'REPLAY_STEP_RESULT',
  REPLAY_COMPLETE: 'REPLAY_COMPLETE',
  REPLAY_ABORTED: 'REPLAY_ABORTED',
  SELECTOR_PICKER_RESULT: 'SELECTOR_PICKER_RESULT',
  CONTENT_EXTRACT_PICKED: 'CONTENT_EXTRACT_PICKED',
  CONTENT_EXTRACT_CANCELLED: 'CONTENT_EXTRACT_CANCELLED',
  UPLOAD_PICKED: 'UPLOAD_PICKED',
  UPLOAD_CANCELLED: 'UPLOAD_CANCELLED',
  HOVER_PICKED: 'HOVER_PICKED',
  HOVER_CANCELLED: 'HOVER_CANCELLED',
  WAIT_ELEMENT_PICKED: 'WAIT_ELEMENT_PICKED',
  WAIT_ELEMENT_CANCELLED: 'WAIT_ELEMENT_CANCELLED',
} as const

// ===== Background ↔ Content Script =====
export const CS_MSG = {
  START_RECORDING: 'CS_START_RECORDING',
  PAUSE_RECORDING: 'CS_PAUSE_RECORDING',
  RESUME_RECORDING: 'CS_RESUME_RECORDING',
  STOP_RECORDING: 'CS_STOP_RECORDING',
  ACTION_CAPTURED: 'CS_ACTION_CAPTURED',
  GET_PAGE_INFO: 'CS_GET_PAGE_INFO',
  GET_PAGE_SNAPSHOT: 'CS_GET_PAGE_SNAPSHOT',
  REPLAY_EXECUTE_ACTION: 'CS_REPLAY_EXECUTE_ACTION',
  START_SELECTOR_PICKER: 'CS_START_SELECTOR_PICKER',
  STOP_SELECTOR_PICKER: 'CS_STOP_SELECTOR_PICKER',
  SELECTOR_PICKED: 'CS_SELECTOR_PICKED',
  INFER_SELECTOR_PATTERN: 'CS_INFER_SELECTOR_PATTERN',
  LOOP_TARGET_PREVIEW_TEST: 'CS_LOOP_TARGET_PREVIEW_TEST',
  LOOP_TARGET_PREVIEW_SCAN: 'CS_LOOP_TARGET_PREVIEW_SCAN',
  START_CONTENT_EXTRACT_PICKER: 'CS_START_CONTENT_EXTRACT_PICKER',
  STOP_CONTENT_EXTRACT_PICKER: 'CS_STOP_CONTENT_EXTRACT_PICKER',
  CONTENT_EXTRACT_PICKED: 'CS_CONTENT_EXTRACT_PICKED',
  CONTENT_EXTRACT_CANCELLED: 'CS_CONTENT_EXTRACT_CANCELLED',
  START_UPLOAD_PICKER: 'CS_START_UPLOAD_PICKER',
  STOP_UPLOAD_PICKER: 'CS_STOP_UPLOAD_PICKER',
  UPLOAD_PICKED: 'CS_UPLOAD_PICKED',
  UPLOAD_CANCELLED: 'CS_UPLOAD_CANCELLED',
  START_HOVER_PICKER: 'CS_START_HOVER_PICKER',
  STOP_HOVER_PICKER: 'CS_STOP_HOVER_PICKER',
  HOVER_PICKED: 'CS_HOVER_PICKED',
  HOVER_CANCELLED: 'CS_HOVER_CANCELLED',
  START_WAIT_ELEMENT_PICKER: 'CS_START_WAIT_ELEMENT_PICKER',
  STOP_WAIT_ELEMENT_PICKER: 'CS_STOP_WAIT_ELEMENT_PICKER',
  WAIT_ELEMENT_PICKED: 'CS_WAIT_ELEMENT_PICKED',
  WAIT_ELEMENT_CANCELLED: 'CS_WAIT_ELEMENT_CANCELLED',
  CAPTURE_VISIBLE_TAB: 'CS_CAPTURE_VISIBLE_TAB',
  TEST_SELECTOR_HIGHLIGHT: 'CS_TEST_SELECTOR_HIGHLIGHT',
} as const
