import type { Branch } from '@/types/branch'
import type { LLMSettings } from '@/types/message'
import { callLLM } from '../analyzer/semantic/llmClient'
import {
  branchesHaveWaitNodes,
  isSchemaParamRequired,
  resolveParamBusinessDescription,
  resolveRegisteredParamName,
  summarizeToolBehavior,
} from './branchCodeGen'

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function generateReadme(
  branches: Branch[],
  toolSetName: string,
  serverFileName: string,
  llmSettings?: LLMSettings,
): Promise<string> {
  const registeredBranches = branches.filter(b => b.registration)

  // Build a brief tool list for LLM context
  const toolListText = registeredBranches
    .map(b => `- ${b.registration!.toolName}: ${b.registration!.toolDescription}`)
    .join('\n')

  // Attempt LLM-enhanced introduction (graceful fallback on any failure)
  let intro = ''
  if (llmSettings?.apiKey && registeredBranches.length > 0) {
    try {
      intro = await generateLLMIntro(toolSetName, toolListText, llmSettings)
    } catch {
      // silently ignore — template intro used below
    }
  }
  if (!intro) {
    intro = generateTemplateIntro(toolSetName, registeredBranches)
  }

  return buildReadme(branches, toolSetName, serverFileName, intro)
}

// ---------------------------------------------------------------------------
// LLM intro generation
// ---------------------------------------------------------------------------

async function generateLLMIntro(
  toolSetName: string,
  toolListText: string,
  settings: LLMSettings,
): Promise<string> {
  const systemPrompt = `You are a technical documentation writer. Your task is to write concise, clear introductions for MCP (Model Context Protocol) server README files. Write in English. Be direct and informative. Do NOT include headings, bullet points, or markdown — return plain text only (2-4 sentences).`

  const userPrompt = `Write a concise introduction for a MCP server named "${toolSetName}".

Available tools:
${toolListText}

The introduction should explain:
1. What this MCP server enables users to do
2. The main automation capabilities it provides

Return plain text only, no markdown formatting.`

  const raw = await callLLM(settings, systemPrompt, userPrompt)
  // Strip any accidental markdown headings or fences
  return raw
    .replace(/^#+\s+.*/gm, '')
    .replace(/```[\s\S]*?```/g, '')
    .trim()
}

function generateTemplateIntro(toolSetName: string, branches: Branch[]): string {
  if (branches.length === 0) {
    return `This MCP server provides browser automation tools generated by YOSO. It uses Playwright to control a Chromium browser and exposes each recorded workflow as an MCP-compatible tool.`
  }

  const toolNames = branches
    .filter(b => b.registration)
    .map(b => `\`${b.registration!.toolName}\``)
    .slice(0, 4)
    .join(', ')

  const more = branches.length > 4 ? ` and ${branches.length - 4} more` : ''
  return `This MCP server provides browser automation for **${toolSetName}**, generated by [YOSO](https://github.com/YosoMCP/yoso-extension). It exposes ${branches.length} tool${branches.length !== 1 ? 's' : ''} — ${toolNames}${more} — letting any MCP-compatible AI client interact with a real browser to automate your workflows.`
}

// ---------------------------------------------------------------------------
// README assembly
// ---------------------------------------------------------------------------

function buildReadme(
  branches: Branch[],
  toolSetName: string,
  serverFileName: string,
  intro: string,
): string {
  const serverName = toKebabCase(toolSetName)
  const sections: string[] = []

  sections.push(buildHeader(toolSetName, intro))
  sections.push(buildServerBoundary())
  sections.push(buildToolsSection(branches))
  sections.push(buildReturnContract(serverName))
  sections.push(buildErrorSemantics())
  sections.push(buildRuntimeAndState(branches))
  sections.push(buildPrerequisites())
  sections.push(buildInstallation(serverFileName))
  sections.push(buildMCPConfig(serverName, serverFileName))
  sections.push(buildTroubleshooting())
  sections.push(buildFooter())

  return sections.join('\n\n---\n\n')
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function buildHeader(toolSetName: string, intro: string): string {
  return `# ${toolSetName} MCP Server

> Generated by [YOSO](https://github.com/YosoMCP/yoso-extension) — You Only Show Once

${intro}`
}

function buildToolsSection(branches: Branch[]): string {
  const registered = branches.filter(b => b.registration)
  if (registered.length === 0) return `## Tools\n\n_No tools registered yet._`

  const toolDocs = registered.map(b => buildToolDoc(b)).join('\n\n')
  return `## Tools\n\n${toolDocs}`
}

function buildToolDoc(branch: Branch): string {
  const reg = branch.registration!
  const lines: string[] = []
  const behavior = summarizeToolBehavior(branch)

  lines.push(`### \`${reg.toolName}\``)
  lines.push('')
  lines.push(reg.toolDescription)
  lines.push('')
  lines.push(`**Applicable scenario:** ${behavior.usageScenario}`)
  lines.push('')
  lines.push('**Side effects:**')
  for (const effect of behavior.sideEffects) {
    lines.push(`- ${effect}`)
  }

  if (branch.params.length > 0) {
    lines.push('')
    lines.push('**Parameters:**')
    lines.push('')
    lines.push('| Name | Type | Required | Default | Description | Enum |')
    lines.push('|------|------|----------|---------|-------------|------|')
    for (const p of branch.params) {
      const name = resolveRegisteredParamName(p, reg)
      const desc = resolveParamBusinessDescription(p)
      const opts = p.enumOptions ? p.enumOptions.map(o => `\`${o}\``).join(', ') : '—'
      const required = isSchemaParamRequired(p) ? 'Yes' : 'No'
      const defaultValue = formatDefaultValue(p.defaultValue)
      lines.push(`| \`${name}\` | \`${p.type}\` | ${required} | ${defaultValue} | ${desc} | ${opts} |`)
    }
  }

  if (branch.returns.length > 0) {
    lines.push('')
    lines.push('**Returns:**')
    for (const r of branch.returns) {
      if (r.extractMode === 'screenshot') {
        lines.push(`- Screenshot saved to \`extract-{timestamp}.png\``)
      } else {
        lines.push(`- Text content from \`${r.selector.slice(0, 60)}${r.selector.length > 60 ? '…' : ''}\``)
      }
    }
  }

  return lines.join('\n')
}

function formatDefaultValue(value: unknown): string {
  if (value === undefined || value === null) return '—'
  if (typeof value === 'string') return `\`${value}\``
  if (typeof value === 'number' || typeof value === 'boolean') return `\`${String(value)}\``
  return `\`${JSON.stringify(value)}\``
}

function buildServerBoundary(): string {
  return `## Server Boundary

### This server does

- Executes validated browser workflows that were recorded in YOSO.
- Exposes each workflow as an MCP tool with typed input schema.
- Runs browser automation through Playwright in a real Chromium session.

### This server does not

- Does not bypass login requirements, captcha, or target platform security checks.
- Does not guarantee workflow stability when website layout or business flow changes.
- Does not support concurrent tool calls in a single server process.`
}

function buildReturnContract(serverName: string): string {
  return `## Return Contract

Tool execution responses are returned as JSON text in MCP \`content[].text\`.

### Success payload

\`\`\`json
{
  "ok": true,
  "data": {},
  "meta": {
    "server": "${serverName}",
    "toolName": "<tool-name>",
    "timestamp": "<ISO-8601>",
    "serverDescription": "<stable string>",
    "boundary": {
      "does": ["..."],
      "doesNot": ["..."]
    },
    "runtime": {
      "sessionBroker": true,
      "timeout": {
        "actionDelayMs": 1500,
        "navigationTimeoutMs": 30000,
        "waitRecoveryMs": 120000
      },
      "concurrency": "single-tool-call-only"
    }
  }
}
\`\`\`

Stable fields for parsing: \`ok\`, \`data\`, \`meta.server\`, \`meta.toolName\`, \`meta.timestamp\`.

### Failure payload

\`\`\`json
{
  "ok": false,
  "error": {
    "code": "RETRYABLE_TIMEOUT",
    "message": "<error-message>",
    "retryable": true,
    "recovery": "retry"
  },
  "meta": {
    "server": "${serverName}",
    "toolName": "<tool-name>",
    "timestamp": "<ISO-8601>"
  }
}
\`\`\`

Stable fields for parsing: \`ok\`, \`error.code\`, \`error.retryable\`, \`error.recovery\`, \`meta.toolName\`.`
}

function buildErrorSemantics(): string {
  return `## Error Semantics

| Error code | Retryable | Meaning | Recommended recovery |
|------------|-----------|---------|----------------------|
| \`RETRYABLE_TIMEOUT\` | Yes | Temporary timeout while waiting for page/UI readiness | Retry the same tool call |
| \`NON_RETRYABLE_AUTH_REQUIRED\` | No | Authentication state is missing or expired | Re-login, then call again |
| \`NON_RETRYABLE_SELECTOR_STALE\` | No | Recorded selector no longer matches current UI | Re-record workflow in YOSO |
| \`NON_RETRYABLE_INVALID_ARGUMENT\` | No | Arguments do not satisfy expected semantics | Correct arguments or re-record |
| \`NON_RETRYABLE_UNKNOWN_TOOL\` | No | Tool name does not exist in current server | Refresh tool list or re-export |
| \`NON_RETRYABLE_UNKNOWN\` | No | Unclassified execution failure | Inspect payload, then re-record if persistent |`
}

function buildRuntimeAndState(branches: Branch[]): string {
  const needsSession = branchesHaveWaitNodes(branches)
  return `## Runtime & State

- **Login/session source:** ${needsSession ? 'Session Broker (persisted Playwright storage state under user home).' : 'No Session Broker persistence is required for this export.'}
- **Timeout behavior:** wait steps use staged timeout recovery (short wait first, then extended wait for manual completion).
- **Concurrency:** one tool call at a time in a single process; avoid parallel invocations.
- **Browser lifecycle:** each tool call closes browser context at the end of execution.`
}

function buildPrerequisites(): string {
  return `## Prerequisites

| Requirement | Version | Notes |
|-------------|---------|-------|
| [Node.js](https://nodejs.org/) | ≥ 18.0.0 | Required to run the server |
| npm | ≥ 9.0.0 | Bundled with Node.js |
| Chromium | latest | Installed automatically by Playwright |`
}

function buildInstallation(serverFileName: string): string {
  return `## Installation

Create a dedicated folder for your MCP server, save \`${serverFileName}\` into it, then run:

\`\`\`bash
# 1. Initialize a Node.js project
npm init -y

# 2. Install runtime dependencies
npm install @modelcontextprotocol/sdk playwright

# 3. Install tsx (TypeScript runner — no build step needed)
npm install -D tsx

# 4. Download the Chromium browser binary
npx playwright install chromium
\`\`\`

### Verify the server starts

\`\`\`bash
npx tsx ${serverFileName}
\`\`\`

> The server communicates over **stdio** (standard input/output). You won't see interactive output when running manually — this is expected. The MCP client connects to it automatically.`
}

function buildMCPConfig(serverName: string, serverFileName: string): string {
  const argPath = `/absolute/path/to/${serverFileName}`

  return `## MCP Client Configuration

Replace \`/absolute/path/to/${serverFileName}\` with the **full absolute path** to your server file.

### Cursor

1. Open **Cursor** → Settings (gear icon) → **MCP**
2. Click **"Add new global MCP server"** to edit \`~/.cursor/mcp.json\`, or create \`.cursor/mcp.json\` in your project root for a project-scoped config:

\`\`\`json
{
  "mcpServers": {
    "${serverName}": {
      "command": "npx",
      "args": ["-y", "tsx", "${argPath}"]
    }
  }
}
\`\`\`

3. Save the file and reload Cursor (**Ctrl+Shift+P** → \`Developer: Reload Window\`)
4. Open a chat — the tools should appear in the MCP panel on the left sidebar.

---

### Claude Code / Claude Desktop

1. For **Claude Desktop**: open top-left menu → **Settings** → **Developer** → **Edit Config**
2. For **Claude Code**: open MCP configuration and add a stdio server entry using the same command/args below.
3. Add your server config:

\`\`\`json
{
  "mcpServers": {
    "${serverName}": {
      "command": "npx",
      "args": ["-y", "tsx", "${argPath}"]
    }
  }
}
\`\`\`

4. Save and restart the client (for Claude Desktop, quit from the system tray and reopen).

---

### Windsurf (Codeium)

Edit \`~/.codeium/windsurf/mcp_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${serverName}": {
      "command": "npx",
      "args": ["-y", "tsx", "${argPath}"]
    }
  }
}
\`\`\`

Restart Windsurf after saving.

---

### Continue.dev

Add to your \`~/.continue/config.json\` under the \`experimental.modelContextProtocolServers\` key:

\`\`\`json
{
  "experimental": {
    "modelContextProtocolServers": [
      {
        "transport": {
          "type": "stdio",
          "command": "npx",
          "args": ["-y", "tsx", "${argPath}"]
        }
      }
    ]
  }
}
\`\`\`

---

### Other MCP Clients (generic stdio config)

Any MCP client that supports the **stdio transport** can use this server. The standard configuration pattern is:

\`\`\`json
{
  "command": "npx",
  "args": ["-y", "tsx", "${argPath}"]
}
\`\`\``
}

function buildTroubleshooting(): string {
  return `## Troubleshooting

| Problem | Solution |
|---------|----------|
| \`Cannot find module '@modelcontextprotocol/sdk'\` | Run \`npm install @modelcontextprotocol/sdk playwright\` in the server folder |
| \`browserType.launch: Executable doesn't exist\` | Run \`npx playwright install chromium\` |
| \`tsx: command not found\` | Run \`npm install -D tsx\` then use \`npx tsx\` |
| \`Top-level await is not supported with the "cjs" output format\` | Add \`"type": "module"\` to your \`package.json\`, or upgrade to \`tsx\` ≥ 4: \`npm install -D tsx@latest\` |
| Server not appearing in MCP client | Verify the absolute path in the config is correct; check the client's MCP logs for errors |
| Browser opens but actions fail | The target website may have changed its layout — re-record in YOSO |
| Timeout errors on slow pages | Increase the \`ACTION_DELAY\` constant at the top of the server file |`
}

function buildFooter(): string {
  return `## About

This MCP server was automatically generated by **[YOSO](https://github.com/YosoMCP/yoso-extension)** (You Only Show Once) — a Chrome extension that records browser interactions and converts them into executable MCP servers powered by Playwright.

- **Project**: [YosoMCP/yoso-extension](https://github.com/YosoMCP/yoso-extension)
- **MCP Specification**: [modelcontextprotocol.io](https://modelcontextprotocol.io)
- **Playwright Docs**: [playwright.dev](https://playwright.dev)`
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function toKebabCase(name: string): string {
  return name
    .toLowerCase()
    .replace(/[\u4e00-\u9fa5]+/g, s => s) // keep Chinese as-is
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'mcp-server'
}
